name: ilebora_empowertech
description: A Flutter package for integrating with Bora Empowertech services. Bora Empowertech is a portal to access various Ilebora services.
version: 0.0.5
homepage: https://github.com/ILEBORA/ilebora-empowertech

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

library:
  name: ilebora_empowertech
  entry-points:
    - lib/ilebora_empowertech.dart